Project import generated by Copybara.
PiperOrigin-RevId: 162346017

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -8,7 +8,7 @@ steps:
   args:
   - '-c'
   - |
-    # find . -type d -maxdepth 1 | grep -Ev "vendor|.git|gopath|integration_tests" | xargs /builder/bin/go.bash test
+    find . -type d -maxdepth 1 | grep -Ev "vendor|.git|gopath|integration_tests" | xargs /builder/bin/go.bash test
 
 # Binary creation.
 - name: 'gcr.io/cloud-builders/go:wheezy'
@@ -18,6 +18,44 @@ steps:
 # run integration tests in a VM.
 - name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: 'bash'
-  args: ['-c', './integration_tests/run_tests_on_vm.sh']
+  args:
+  - '-c'
+  - |
+    DATE=`date +%Y%m%d-%H%M%S`
+    GCS_PATH=gs://container-builder-local-test/$$DATE
+    GCS_LOGS_PATH=gs://container-builder-local-test-logs/$$DATE
+    gsutil -m copy container-builder-local $$GCS_PATH/
+    gsutil -m copy ./integration_tests/* $$GCS_PATH/
+
+    gcloud config set compute/zone us-central1-f
+    instance_name=ubuntu-integration-tests-$$DATE
+    gcloud compute instances create $$instance_name \
+      --image-family=ubuntu-1404-lts \
+      --image-project=ubuntu-os-cloud \
+      --machine-type=n1-standard-2 \
+      --scopes default,userinfo-email,useraccounts-ro,cloud-platform \
+      --metadata-from-file startup-script=integration_tests/gce_startup_script.sh \
+      --metadata zone=us-central1-f,gcs_path=$$GCS_PATH,gcs_logs_path=$$GCS_LOGS_PATH || exit
+
+    # Wait until either the success or failure file is written to GCS.
+    status=0
+    while true
+    do
+      if gsutil stat $$GCS_LOGS_PATH/success.txt 2> /dev/null; then
+        gsutil cat $$GCS_LOGS_PATH/success.txt
+        break
+      fi
+      if gsutil stat $$GCS_LOGS_PATH/failure.txt 2> /dev/null; then
+        gsutil cat $$GCS_LOGS_PATH/failure.txt
+        status=1
+        break
+      fi
+      echo "Tests are still running, checking in a few seconds..."
+      sleep 5
+    done
+
+    # Delete the VM and return the status
+    gcloud compute instances delete $$instance_name --quiet
+    exit $$status
 
 
